name: Deploy Django app to EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
  TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}
  TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Plan Terraform
        id: plan
        run: |
          cd terraform
          terraform plan -out=plan.tfplan

      - name: Apply Terraform
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve plan.tfplan
        env:
          TF_CLI_AUTO_APPROVE: 1

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Configure EC2 instance
        run: ansible-playbook playbook.yml -i "${{ steps.apply.outputs.public_ip }},"
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

      - name: Clone repository
        run: |
          cd ~
          git clone https://github.com/saurav-kumar-mce/ec2-django.git

      - name: Install dependencies
        run: |
          cd ~/django-ec2
          pip install -r requirements.txt

      - name: Apply migrations
        run: |
          cd ~/django-ec2
          python manage.py migrate

      - name: Run Django server
        run: |
          cd ~/django-ec2
          python manage.py runserver 0.0.0.0:8000
