name: Deploy Django app to EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
  TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}
  TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
  EC2_INSTANCE_USERNAME: ubuntu
  EC2_INSTANCE_PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init \
            -backend-config="bucket=django-ec2-bucket" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"

      - name: Plan Terraform
        id: plan
        run: |
          cd terraform
          terraform plan -out=plan.tfplan

      - name: Apply Terraform
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve plan.tfplan
        env:
          TF_CLI_AUTO_APPROVE: 1
          
      - name: Set private key file permissions
        run: |
          echo "${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}" > django-new.pem
          chmod 400 django-new.pem
        shell: bash

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3   

      - name: SSH into server and execute remote script
        uses: jakejarvis/ssh-remote-script@4.3.0
        with:
          command: |
            sudo apt-get update
            sudo apt-get install -y ansible
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          SSH_USERNAME: ubuntu
          SSH_HOST: 3.112.209.2



      - name: Configure EC2 instance
        run: ansible-playbook ansible/playbook.yml -i "${{ steps.apply.outputs.public_ip }},"
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

      - name: Clone repository
        run: |
          cd ~
          git clone https://github.com/saurav-kumar-mce/ec2-django.git

      - name: Install dependencies
        run: |
          cd ~/ec2-django
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install django
          python3 manage.py makemigrations

      - name: Apply migrations
        run: |
          cd ~/ec2-django
          python manage.py migrate

      - name: Run Django server
        run: |
          cd ~/ec2-django
          python manage.py runserver 0.0.0.0:8000
