name: Deploy Django app to EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
  TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}
  TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
  EC2_INSTANCE_USERNAME: ubuntu
  EC2_INSTANCE_PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init \
            -backend-config="bucket=django-ec2-bucket" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"

      - name: Plan Terraform
        id: plan
        run: |
          cd terraform
          terraform plan -out=plan.tfplan

      - name: Apply Terraform
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve plan.tfplan
        env:
          TF_CLI_AUTO_APPROVE: 1
          
      - name: Set private key file permissions
        run: |
          echo "${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}" > django-new.pem
          chmod 400 django-new.pem
        shell: bash

      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2
        with:
          version: 2

      - name: Copy files to EC2 instance
        run: |
          scp -i django-new.pem -o StrictHostKeyChecking=no -r ./* ${{ env.EC2_INSTANCE_USERNAME }}@${{ steps.apply.outputs.public_ip }}:/home/ubuntu/
        shell: bash

      - name: SSH into EC2 instance and install dependencies
        run: |
          ssh -i django-new.pem -o StrictHostKeyChecking=no ${{ env.EC2_INSTANCE_USERNAME }}@${{ steps.apply.outputs.public_ip }} 'sudo apt-get update && sudo apt-get install -y python3-pip && sudo pip3 install django'
          ssh -i django-new.pem -o StrictHostKeyChecking=no ${{ env.EC2_INSTANCE_USERNAME }}@${{ steps.apply.outputs.public_ip }} 'cd /home/ubuntu && python3 manage.py makemigrations && python3 manage.py migrate'
          ssh -i django-new.pem -o StrictHostKeyChecking=no ${{ env.EC2_INSTANCE_USERNAME }}@${{ steps.apply.outputs.public_ip }} 'cd /home/ubuntu && nohup python3 manage.py runserver 0.0.0.0:8000 &'
        shell: bash
